sudo: false

git:
  depth: 5

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

script:
  - npm run test:cov

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" = "10" ]]; then npm run coveralls; fi

cache:
  directories:
    - node_modules

notifications:
  email: false
