version: "{build}"

clone_depth: 5

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node -v
  - npm -v
  - npm test

build: off

cache:
  - node_modules -> appveyor.yml,package.json,package-lock.json
